"""Add sitemap_config to scraper_configs

Revision ID: 64192ec3a278
Revises: 001_initial
Create Date: 2026-01-28 11:22:37.542456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64192ec3a278'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Permissions granted to this API key',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('api_keys', 'rate_limit',
               existing_type=sa.INTEGER(),
               comment='Requests per minute',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.drop_constraint(op.f('api_keys_key_hash_key'), 'api_keys', type_='unique')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.drop_constraint(op.f('categories_slug_key'), 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_constraint(op.f('categories_parent_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    op.create_index('ix_products_fulltext', 'products', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_constraint(op.f('products_website_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'websites', ['website_id'], ['id'])
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.alter_column('scrape_logs', 'errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of errors encountered during scrape',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(op.f('scrape_logs_website_id_fkey'), 'scrape_logs', type_='foreignkey')
    op.create_foreign_key(None, 'scrape_logs', 'websites', ['website_id'], ['id'])
    op.add_column('scraper_configs', sa.Column('sitemap_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Sitemap URL and filtering patterns'))
    op.alter_column('scraper_configs', 'selectors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='CSS/XPath selectors for extracting data',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('scraper_configs', 'pagination_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Pagination strategy and selectors',
               existing_nullable=True)
    op.alter_column('scraper_configs', 'auth_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Login/auth configuration',
               existing_nullable=True)
    op.drop_constraint(op.f('scraper_configs_website_id_fkey'), 'scraper_configs', type_='foreignkey')
    op.create_foreign_key(None, 'scraper_configs', 'websites', ['website_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scraper_configs', type_='foreignkey')
    op.create_foreign_key(op.f('scraper_configs_website_id_fkey'), 'scraper_configs', 'websites', ['website_id'], ['id'], ondelete='CASCADE')
    op.alter_column('scraper_configs', 'auth_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Login/auth configuration',
               existing_nullable=True)
    op.alter_column('scraper_configs', 'pagination_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Pagination strategy and selectors',
               existing_nullable=True)
    op.alter_column('scraper_configs', 'selectors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='CSS/XPath selectors for extracting data',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('scraper_configs', 'sitemap_config')
    op.drop_constraint(None, 'scrape_logs', type_='foreignkey')
    op.create_foreign_key(op.f('scrape_logs_website_id_fkey'), 'scrape_logs', 'websites', ['website_id'], ['id'], ondelete='CASCADE')
    op.alter_column('scrape_logs', 'errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of errors encountered during scrape',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('products_website_id_fkey'), 'products', 'websites', ['website_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_products_fulltext', table_name='products', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_parent_id_fkey'), 'categories', 'categories', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_unique_constraint(op.f('categories_slug_key'), 'categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_unique_constraint(op.f('api_keys_key_hash_key'), 'api_keys', ['key_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('api_keys', 'rate_limit',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Requests per minute',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('api_keys', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Permissions granted to this API key',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
